// ============================================================
// Component Registry — ICG Design System + MUI Layout components
// ============================================================
import type { ComponentMeta, ComponentCategory } from '../../store/types';

export const categories: ComponentCategory[] = [
  'Inputs',
  'Data Display',
  'Surfaces',
  'Navigation',
  'Feedback',
  'Layout',
];

export const componentRegistry: ComponentMeta[] = [
  // ── Inputs ───────────────────────────────────────────────
  {
    type: 'Button',
    displayName: 'Button',
    category: 'Inputs',
    icon: 'SmartButton',
    isContainer: false,
    defaultProps: { label: 'Button', type: 'primary', size: 'middle', disabled: false, danger: false },
    defaultSx: {},
    defaultSize: { width: 120, height: 40 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Button' },
      { name: 'type', label: 'Type', type: 'select', options: ['primary', 'default', 'dashed', 'text', 'link'], defaultValue: 'primary' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'middle', 'large'], defaultValue: 'middle' },
      { name: 'danger', label: 'Danger', type: 'boolean', defaultValue: false },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
      { name: 'block', label: 'Block', type: 'boolean', defaultValue: false },
      { name: 'shape', label: 'Shape', type: 'select', options: ['default', 'circle', 'round'], defaultValue: 'default' },
    ],
  },
  {
    type: 'IconButton',
    displayName: 'Icon Button',
    category: 'Inputs',
    icon: 'TouchApp',
    isContainer: false,
    defaultProps: { iconType: 'star', type: 'primary', shape: 'circle', size: 'middle', disabled: false },
    defaultSx: {},
    defaultSize: { width: 48, height: 48 },
    propSchema: [
      { name: 'iconType', label: 'Icon', type: 'text', defaultValue: 'star' },
      { name: 'type', label: 'Type', type: 'select', options: ['primary', 'default', 'dashed', 'text', 'link'], defaultValue: 'primary' },
      { name: 'shape', label: 'Shape', type: 'select', options: ['default', 'circle', 'round'], defaultValue: 'circle' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'middle', 'large'], defaultValue: 'middle' },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'ButtonGroup',
    displayName: 'Button Group',
    category: 'Inputs',
    icon: 'ViewStream',
    isContainer: false,
    defaultProps: { buttons: ['One', 'Two', 'Three'], size: 'middle' },
    defaultSx: {},
    defaultSize: { width: 260, height: 40 },
    propSchema: [
      { name: 'buttons', label: 'Buttons', type: 'list', defaultValue: ['One', 'Two', 'Three'] },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'middle', 'large'], defaultValue: 'middle' },
    ],
  },
  {
    type: 'TextField',
    displayName: 'Input',
    category: 'Inputs',
    icon: 'TextFields',
    isContainer: false,
    defaultProps: { placeholder: 'Enter text…', size: 'middle', disabled: false, allowClear: false },
    defaultSx: {},
    defaultSize: { width: 240, height: 40 },
    propSchema: [
      { name: 'placeholder', label: 'Placeholder', type: 'text', defaultValue: 'Enter text…' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'middle', 'large'], defaultValue: 'middle' },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
      { name: 'allowClear', label: 'Allow Clear', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Select',
    displayName: 'Select',
    category: 'Inputs',
    icon: 'ArrowDropDownCircle',
    isContainer: false,
    defaultProps: { placeholder: 'Select…', options: ['Option 1', 'Option 2', 'Option 3'], size: 'middle', disabled: false, allowClear: false, showSearch: false },
    defaultSx: {},
    defaultSize: { width: 240, height: 40 },
    propSchema: [
      { name: 'placeholder', label: 'Placeholder', type: 'text', defaultValue: 'Select…' },
      { name: 'options', label: 'Options', type: 'list', defaultValue: ['Option 1', 'Option 2', 'Option 3'] },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'middle', 'large'], defaultValue: 'middle' },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
      { name: 'allowClear', label: 'Allow Clear', type: 'boolean', defaultValue: false },
      { name: 'showSearch', label: 'Show Search', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Checkbox',
    displayName: 'Checkbox',
    category: 'Inputs',
    icon: 'CheckBox',
    isContainer: false,
    defaultProps: { label: 'Check me', checked: false, disabled: false },
    defaultSx: {},
    defaultSize: { width: 180, height: 32 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Check me' },
      { name: 'checked', label: 'Checked', type: 'boolean', defaultValue: false },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Radio',
    displayName: 'Radio Group',
    category: 'Inputs',
    icon: 'RadioButtonChecked',
    isContainer: false,
    defaultProps: { label: 'Options', options: ['Option A', 'Option B', 'Option C'], optionType: 'default', buttonStyle: 'outline' },
    defaultSx: {},
    defaultSize: { width: 200, height: 130 },
    propSchema: [
      { name: 'label', label: 'Group Label', type: 'text', defaultValue: 'Options' },
      { name: 'options', label: 'Options', type: 'list', defaultValue: ['Option A', 'Option B', 'Option C'] },
      { name: 'optionType', label: 'Option Type', type: 'select', options: ['default', 'button'], defaultValue: 'default' },
      { name: 'buttonStyle', label: 'Button Style', type: 'select', options: ['outline', 'solid'], defaultValue: 'outline' },
    ],
  },
  {
    type: 'Switch',
    displayName: 'Switch',
    category: 'Inputs',
    icon: 'ToggleOn',
    isContainer: false,
    defaultProps: { label: 'Toggle me', checked: false, disabled: false, size: 'default' },
    defaultSx: {},
    defaultSize: { width: 180, height: 32 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Toggle me' },
      { name: 'checked', label: 'Checked', type: 'boolean', defaultValue: false },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
      { name: 'size', label: 'Size', type: 'select', options: ['default', 'small'], defaultValue: 'default' },
    ],
  },
  {
    type: 'Slider',
    displayName: 'Slider',
    category: 'Inputs',
    icon: 'LinearScale',
    isContainer: false,
    defaultProps: { value: 50, min: 0, max: 100, step: 1, disabled: false },
    defaultSx: {},
    defaultSize: { width: 240, height: 44 },
    propSchema: [
      { name: 'value', label: 'Value', type: 'number', defaultValue: 50 },
      { name: 'min', label: 'Min', type: 'number', defaultValue: 0 },
      { name: 'max', label: 'Max', type: 'number', defaultValue: 100 },
      { name: 'step', label: 'Step', type: 'number', defaultValue: 1 },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'DatePicker',
    displayName: 'Date Picker',
    category: 'Inputs',
    icon: 'CalendarMonth',
    isContainer: false,
    defaultProps: { placeholder: 'Select date', size: 'middle', disabled: false, picker: 'date' },
    defaultSx: {},
    defaultSize: { width: 240, height: 40 },
    propSchema: [
      { name: 'placeholder', label: 'Placeholder', type: 'text', defaultValue: 'Select date' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'middle', 'large'], defaultValue: 'middle' },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
      { name: 'picker', label: 'Picker', type: 'select', options: ['date', 'week', 'month', 'quarter', 'year'], defaultValue: 'date' },
    ],
  },
  {
    type: 'Upload',
    displayName: 'Upload',
    category: 'Inputs',
    icon: 'CloudUpload',
    isContainer: false,
    defaultProps: { text: 'Click to Upload', hint: 'Support single or bulk upload', listType: 'text' },
    defaultSx: {},
    defaultSize: { width: 240, height: 60 },
    propSchema: [
      { name: 'text', label: 'Button Text', type: 'text', defaultValue: 'Click to Upload' },
      { name: 'hint', label: 'Hint Text', type: 'text', defaultValue: 'Support single or bulk upload' },
      { name: 'listType', label: 'List Type', type: 'select', options: ['text', 'picture', 'picture-card'], defaultValue: 'text' },
    ],
  },

  // ── Data Display ─────────────────────────────────────────
  {
    type: 'Typography',
    displayName: 'Text',
    category: 'Data Display',
    icon: 'Title',
    isContainer: false,
    defaultProps: { text: 'Typography Text', level: 'body', align: 'left' },
    defaultSx: {},
    defaultSize: { width: 260, height: 32 },
    propSchema: [
      { name: 'text', label: 'Text', type: 'text', defaultValue: 'Typography Text' },
      { name: 'level', label: 'Level', type: 'select', options: ['h1', 'h2', 'h3', 'h4', 'h5', 'body', 'caption'], defaultValue: 'body' },
      { name: 'align', label: 'Align', type: 'select', options: ['left', 'center', 'right'], defaultValue: 'left' },
    ],
  },
  {
    type: 'Avatar',
    displayName: 'Avatar',
    category: 'Data Display',
    icon: 'AccountCircle',
    isContainer: false,
    defaultProps: { text: 'AB', shape: 'circle', size: 'default', bgColor: '#1976d2' },
    defaultSx: {},
    defaultSize: { width: 48, height: 48 },
    propSchema: [
      { name: 'text', label: 'Initials', type: 'text', defaultValue: 'AB' },
      { name: 'shape', label: 'Shape', type: 'select', options: ['circle', 'square'], defaultValue: 'circle' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'default', 'large'], defaultValue: 'default' },
      { name: 'bgColor', label: 'Background', type: 'color', defaultValue: '#1976d2' },
    ],
  },
  {
    type: 'Badge',
    displayName: 'Badge',
    category: 'Data Display',
    icon: 'NotificationsActive',
    isContainer: false,
    defaultProps: { count: 4, status: 'error', dot: false, showZero: false },
    defaultSx: {},
    defaultSize: { width: 52, height: 52 },
    propSchema: [
      { name: 'count', label: 'Count', type: 'number', defaultValue: 4 },
      { name: 'status', label: 'Status', type: 'select', options: ['success', 'processing', 'default', 'error', 'warning'], defaultValue: 'error' },
      { name: 'dot', label: 'Dot', type: 'boolean', defaultValue: false },
      { name: 'showZero', label: 'Show Zero', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Tag',
    displayName: 'Tag',
    category: 'Data Display',
    icon: 'Label',
    isContainer: false,
    defaultProps: { label: 'Tag', color: 'blue', closable: false, bordered: true },
    defaultSx: {},
    defaultSize: { width: 80, height: 28 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Tag' },
      { name: 'color', label: 'Color', type: 'select', options: ['blue', 'green', 'red', 'orange', 'gold', 'cyan', 'purple', 'magenta', 'default'], defaultValue: 'blue' },
      { name: 'closable', label: 'Closable', type: 'boolean', defaultValue: false },
      { name: 'bordered', label: 'Bordered', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'Divider',
    displayName: 'Divider',
    category: 'Data Display',
    icon: 'HorizontalRule',
    isContainer: false,
    defaultProps: { type: 'horizontal', dashed: false, text: '', orientation: 'center' },
    defaultSx: {},
    defaultSize: { width: 300, height: 20 },
    propSchema: [
      { name: 'type', label: 'Type', type: 'select', options: ['horizontal', 'vertical'], defaultValue: 'horizontal' },
      { name: 'dashed', label: 'Dashed', type: 'boolean', defaultValue: false },
      { name: 'text', label: 'Text', type: 'text', defaultValue: '' },
      { name: 'orientation', label: 'Orientation', type: 'select', options: ['left', 'center', 'right'], defaultValue: 'center' },
    ],
  },
  {
    type: 'List',
    displayName: 'List',
    category: 'Data Display',
    icon: 'FormatListBulleted',
    isContainer: false,
    defaultProps: { items: ['Item 1', 'Item 2', 'Item 3'], bordered: false, size: 'default' },
    defaultSx: {},
    defaultSize: { width: 280, height: 160 },
    propSchema: [
      { name: 'items', label: 'Items', type: 'list', defaultValue: ['Item 1', 'Item 2', 'Item 3'] },
      { name: 'bordered', label: 'Bordered', type: 'boolean', defaultValue: false },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'default', 'large'], defaultValue: 'default' },
    ],
  },
  {
    type: 'Table',
    displayName: 'Table',
    category: 'Data Display',
    icon: 'TableChart',
    isContainer: false,
    defaultProps: { columns: ['#', 'Name', 'Email', 'Role'], rows: ['1,Alice,alice@mail.com,Admin', '2,Bob,bob@mail.com,User'], size: 'middle', bordered: false },
    defaultSx: {},
    defaultSize: { width: 420, height: 220 },
    propSchema: [
      { name: 'columns', label: 'Columns', type: 'list', defaultValue: ['#', 'Name', 'Email', 'Role'] },
      { name: 'rows', label: 'Rows (comma-separated)', type: 'list', defaultValue: ['1,Alice,alice@mail.com,Admin', '2,Bob,bob@mail.com,User'] },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'middle', 'large'], defaultValue: 'middle' },
      { name: 'bordered', label: 'Bordered', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Tooltip',
    displayName: 'Tooltip',
    category: 'Data Display',
    icon: 'Info',
    isContainer: false,
    defaultProps: { title: 'Tooltip text', placement: 'top' },
    defaultSx: {},
    defaultSize: { width: 120, height: 40 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Tooltip text' },
      { name: 'placement', label: 'Placement', type: 'select', options: ['top', 'bottom', 'left', 'right', 'topLeft', 'topRight', 'bottomLeft', 'bottomRight'], defaultValue: 'top' },
    ],
  },
  {
    type: 'Image',
    displayName: 'Image',
    category: 'Data Display',
    icon: 'Image',
    isContainer: false,
    defaultProps: { src: 'https://via.placeholder.com/300x200', alt: 'placeholder', objectFit: 'cover' },
    defaultSx: {},
    defaultSize: { width: 300, height: 200 },
    propSchema: [
      { name: 'src', label: 'Source URL', type: 'text', defaultValue: 'https://via.placeholder.com/300x200' },
      { name: 'alt', label: 'Alt Text', type: 'text', defaultValue: 'placeholder' },
      { name: 'objectFit', label: 'Object Fit', type: 'select', options: ['cover', 'contain', 'fill', 'none'], defaultValue: 'cover' },
    ],
  },
  {
    type: 'Carousel',
    displayName: 'Carousel',
    category: 'Data Display',
    icon: 'ViewCarousel',
    isContainer: false,
    defaultProps: { slides: ['Slide 1', 'Slide 2', 'Slide 3'], autoplay: false, dots: true, effect: 'scrollx' },
    defaultSx: {},
    defaultSize: { width: 400, height: 200 },
    propSchema: [
      { name: 'slides', label: 'Slides', type: 'list', defaultValue: ['Slide 1', 'Slide 2', 'Slide 3'] },
      { name: 'autoplay', label: 'Autoplay', type: 'boolean', defaultValue: false },
      { name: 'dots', label: 'Dots', type: 'boolean', defaultValue: true },
      { name: 'effect', label: 'Effect', type: 'select', options: ['scrollx', 'fade'], defaultValue: 'scrollx' },
    ],
  },

  // ── Surfaces ─────────────────────────────────────────────
  {
    type: 'Card',
    displayName: 'Card',
    category: 'Surfaces',
    icon: 'CreditCard',
    isContainer: true,
    defaultProps: { title: 'Card Title', bordered: true, hoverable: false, size: 'default' },
    defaultSx: {},
    defaultSize: { width: 320, height: 180 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Card Title' },
      { name: 'bordered', label: 'Bordered', type: 'boolean', defaultValue: true },
      { name: 'hoverable', label: 'Hoverable', type: 'boolean', defaultValue: false },
      { name: 'size', label: 'Size', type: 'select', options: ['default', 'small'], defaultValue: 'default' },
    ],
  },
  {
    type: 'Paper',
    displayName: 'Section',
    category: 'Surfaces',
    icon: 'Description',
    isContainer: true,
    defaultProps: { title: 'Section Title', bordered: true, size: 'default' },
    defaultSx: { p: 2 },
    defaultSize: { width: 300, height: 200 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Section Title' },
      { name: 'bordered', label: 'Bordered', type: 'boolean', defaultValue: true },
      { name: 'size', label: 'Size', type: 'select', options: ['default', 'small', 'large'], defaultValue: 'default' },
    ],
  },
  {
    type: 'Accordion',
    displayName: 'Collapse',
    category: 'Surfaces',
    icon: 'ExpandMore',
    isContainer: false,
    defaultProps: { title: 'Collapse Panel', content: 'Panel content goes here.', defaultExpanded: false, bordered: true, accordion: true },
    defaultSx: {},
    defaultSize: { width: 320, height: 56 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Collapse Panel' },
      { name: 'content', label: 'Content', type: 'text', defaultValue: 'Panel content goes here.' },
      { name: 'defaultExpanded', label: 'Default Expanded', type: 'boolean', defaultValue: false },
      { name: 'bordered', label: 'Bordered', type: 'boolean', defaultValue: true },
    ],
  },

  // -- Navigation ---------------------------------------------------
  {
    type: 'AppBar',
    displayName: 'Menu Bar',
    category: 'Navigation',
    icon: 'WebAsset',
    isContainer: false,
    defaultProps: { items: ['Home', 'Products', 'About', 'Contact'], mode: 'horizontal', theme: 'dark' },
    defaultSx: {},
    defaultSize: { width: 400, height: 48 },
    propSchema: [
      { name: 'items', label: 'Items', type: 'list', defaultValue: ['Home', 'Products', 'About', 'Contact'] },
      { name: 'mode', label: 'Mode', type: 'select', options: ['horizontal', 'vertical', 'inline'], defaultValue: 'horizontal' },
      { name: 'theme', label: 'Theme', type: 'select', options: ['light', 'dark'], defaultValue: 'dark' },
    ],
  },
  {
    type: 'Tabs',
    displayName: 'Tabs',
    category: 'Navigation',
    icon: 'Tab',
    isContainer: false,
    defaultProps: { tabs: ['Tab 1', 'Tab 2', 'Tab 3'], type: 'line', size: 'default', tabPosition: 'top' },
    defaultSx: {},
    defaultSize: { width: 360, height: 48 },
    propSchema: [
      { name: 'tabs', label: 'Tabs', type: 'list', defaultValue: ['Tab 1', 'Tab 2', 'Tab 3'] },
      { name: 'type', label: 'Type', type: 'select', options: ['line', 'card', 'editable-card'], defaultValue: 'line' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'default', 'large'], defaultValue: 'default' },
      { name: 'tabPosition', label: 'Position', type: 'select', options: ['top', 'right', 'bottom', 'left'], defaultValue: 'top' },
    ],
  },
  {
    type: 'Breadcrumbs',
    displayName: 'Breadcrumb',
    category: 'Navigation',
    icon: 'ChevronRight',
    isContainer: false,
    defaultProps: { items: ['Home', 'Category', 'Current'], separator: '/' },
    defaultSx: {},
    defaultSize: { width: 280, height: 32 },
    propSchema: [
      { name: 'items', label: 'Items', type: 'list', defaultValue: ['Home', 'Category', 'Current'] },
      { name: 'separator', label: 'Separator', type: 'text', defaultValue: '/' },
    ],
  },
  {
    type: 'Drawer',
    displayName: 'Side Menu',
    category: 'Navigation',
    icon: 'Menu',
    isContainer: false,
    defaultProps: { menuItems: ['Dashboard', 'Settings > Profile', 'Settings > Account', 'Settings > Privacy', 'Reports'], title: 'Menu', mode: 'inline', theme: 'light' },
    defaultSx: {},
    defaultSize: { width: 240, height: 400 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Menu' },
      { name: 'menuItems', label: 'Menu Items', type: 'list', defaultValue: ['Dashboard', 'Settings > Profile', 'Settings > Account', 'Settings > Privacy', 'Reports'] },
      { name: 'mode', label: 'Mode', type: 'select', options: ['inline', 'vertical'], defaultValue: 'inline' },
      { name: 'theme', label: 'Theme', type: 'select', options: ['light', 'dark'], defaultValue: 'light' },
    ],
  },
  {
    type: 'Pagination',
    displayName: 'Pagination',
    category: 'Navigation',
    icon: 'MoreHoriz',
    isContainer: false,
    defaultProps: { total: 100, pageSize: 10, size: 'default', showSizeChanger: false, showQuickJumper: false, simple: false },
    defaultSx: {},
    defaultSize: { width: 320, height: 40 },
    propSchema: [
      { name: 'total', label: 'Total Items', type: 'number', defaultValue: 100 },
      { name: 'pageSize', label: 'Page Size', type: 'number', defaultValue: 10 },
      { name: 'size', label: 'Size', type: 'select', options: ['default', 'small'], defaultValue: 'default' },
      { name: 'showSizeChanger', label: 'Size Changer', type: 'boolean', defaultValue: false },
      { name: 'showQuickJumper', label: 'Quick Jumper', type: 'boolean', defaultValue: false },
      { name: 'simple', label: 'Simple', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Stepper',
    displayName: 'Steps',
    category: 'Navigation',
    icon: 'LinearScale',
    isContainer: false,
    defaultProps: { steps: ['Step 1', 'Step 2', 'Step 3'], current: 0, direction: 'horizontal', size: 'default' },
    defaultSx: {},
    defaultSize: { width: 400, height: 72 },
    propSchema: [
      { name: 'steps', label: 'Steps', type: 'list', defaultValue: ['Step 1', 'Step 2', 'Step 3'] },
      { name: 'current', label: 'Current Step', type: 'number', defaultValue: 0 },
      { name: 'direction', label: 'Direction', type: 'select', options: ['horizontal', 'vertical'], defaultValue: 'horizontal' },
      { name: 'size', label: 'Size', type: 'select', options: ['default', 'small'], defaultValue: 'default' },
    ],
  },
  {
    type: 'Dropdown',
    displayName: 'Dropdown',
    category: 'Navigation',
    icon: 'ArrowDropDown',
    isContainer: false,
    defaultProps: { label: 'Dropdown', items: ['Action 1', 'Action 2', 'Action 3'], placement: 'bottomLeft', trigger: 'hover' },
    defaultSx: {},
    defaultSize: { width: 120, height: 40 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Dropdown' },
      { name: 'items', label: 'Items', type: 'list', defaultValue: ['Action 1', 'Action 2', 'Action 3'] },
      { name: 'placement', label: 'Placement', type: 'select', options: ['bottomLeft', 'bottomRight', 'topLeft', 'topRight', 'bottom', 'top'], defaultValue: 'bottomLeft' },
      { name: 'trigger', label: 'Trigger', type: 'select', options: ['hover', 'click'], defaultValue: 'hover' },
    ],
  },

  // ── Feedback ─────────────────────────────────────────────
  {
    type: 'Alert',
    displayName: 'Alert',
    category: 'Feedback',
    icon: 'Warning',
    isContainer: false,
    defaultProps: { type: 'info', text: 'This is an alert.', closable: false, showIcon: true, banner: false },
    defaultSx: {},
    defaultSize: { width: 320, height: 48 },
    propSchema: [
      { name: 'text', label: 'Text', type: 'text', defaultValue: 'This is an alert.' },
      { name: 'type', label: 'Type', type: 'select', options: ['info', 'success', 'warning', 'danger'], defaultValue: 'info' },
      { name: 'closable', label: 'Closable', type: 'boolean', defaultValue: false },
      { name: 'showIcon', label: 'Show Icon', type: 'boolean', defaultValue: true },
      { name: 'banner', label: 'Banner', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Notification',
    displayName: 'Notification',
    category: 'Feedback',
    icon: 'Announcement',
    isContainer: false,
    defaultProps: { message: 'Notification', description: 'This is a notification message.', type: 'info', placement: 'topRight' },
    defaultSx: {},
    defaultSize: { width: 320, height: 80 },
    propSchema: [
      { name: 'message', label: 'Message', type: 'text', defaultValue: 'Notification' },
      { name: 'description', label: 'Description', type: 'text', defaultValue: 'This is a notification message.' },
      { name: 'type', label: 'Type', type: 'select', options: ['info', 'success', 'warning', 'error'], defaultValue: 'info' },
      { name: 'placement', label: 'Placement', type: 'select', options: ['topLeft', 'topRight', 'bottomLeft', 'bottomRight'], defaultValue: 'topRight' },
    ],
  },
  {
    type: 'Modal',
    displayName: 'Modal',
    category: 'Feedback',
    icon: 'OpenInNew',
    isContainer: false,
    defaultProps: { title: 'Modal Title', content: 'Modal content text.', okText: 'OK', cancelText: 'Cancel', centered: false },
    defaultSx: {},
    defaultSize: { width: 400, height: 200 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Modal Title' },
      { name: 'content', label: 'Content', type: 'text', defaultValue: 'Modal content text.' },
      { name: 'okText', label: 'OK Text', type: 'text', defaultValue: 'OK' },
      { name: 'cancelText', label: 'Cancel Text', type: 'text', defaultValue: 'Cancel' },
      { name: 'centered', label: 'Centered', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Loading',
    displayName: 'Loading',
    category: 'Feedback',
    icon: 'Refresh',
    isContainer: false,
    defaultProps: { spinning: true, size: 'default', tip: '' },
    defaultSx: {},
    defaultSize: { width: 60, height: 60 },
    propSchema: [
      { name: 'spinning', label: 'Spinning', type: 'boolean', defaultValue: true },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'default', 'large'], defaultValue: 'default' },
      { name: 'tip', label: 'Tip Text', type: 'text', defaultValue: '' },
    ],
  },
  {
    type: 'Popover',
    displayName: 'Popover',
    category: 'Feedback',
    icon: 'ChatBubble',
    isContainer: false,
    defaultProps: { title: 'Popover', content: 'Popover content here.', trigger: 'hover', placement: 'top' },
    defaultSx: {},
    defaultSize: { width: 120, height: 40 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Popover' },
      { name: 'content', label: 'Content', type: 'text', defaultValue: 'Popover content here.' },
      { name: 'trigger', label: 'Trigger', type: 'select', options: ['hover', 'click', 'focus'], defaultValue: 'hover' },
      { name: 'placement', label: 'Placement', type: 'select', options: ['top', 'bottom', 'left', 'right', 'topLeft', 'topRight', 'bottomLeft', 'bottomRight'], defaultValue: 'top' },
    ],
  },

  // -- Layout (MUI — kept as-is) ---------------------------------
  {
    type: 'Box',
    displayName: 'Box',
    category: 'Layout',
    icon: 'CheckBoxOutlineBlank',
    isContainer: true,
    defaultProps: {},
    defaultSx: { p: 2, border: '1px dashed grey' },
    defaultSize: { width: 300, height: 200 },
    propSchema: [],
  },
  {
    type: 'Stack',
    displayName: 'Stack',
    category: 'Layout',
    icon: 'ViewAgenda',
    isContainer: true,
    defaultProps: { direction: 'column', spacing: 2, alignItems: 'stretch', justifyContent: 'flex-start' },
    defaultSx: { p: 1 },
    defaultSize: { width: 300, height: 200 },
    propSchema: [
      { name: 'direction', label: 'Direction', type: 'select', options: ['row', 'column', 'row-reverse', 'column-reverse'], defaultValue: 'column' },
      { name: 'spacing', label: 'Spacing', type: 'number', defaultValue: 2 },
      { name: 'alignItems', label: 'Align Items', type: 'select', options: ['flex-start', 'center', 'flex-end', 'stretch', 'baseline'], defaultValue: 'stretch' },
      { name: 'justifyContent', label: 'Justify', type: 'select', options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around', 'space-evenly'], defaultValue: 'flex-start' },
    ],
  },
  {
    type: 'Grid',
    displayName: 'Grid',
    category: 'Layout',
    icon: 'GridView',
    isContainer: true,
    defaultProps: { columns: 12, cols: 3, spacing: 2 },
    defaultSx: {},
    defaultSize: { width: 400, height: 200 },
    propSchema: [
      { name: 'cols', label: 'Columns', type: 'select', options: ['1', '2', '3', '4', '6'], defaultValue: '3' },
      { name: 'spacing', label: 'Spacing', type: 'number', defaultValue: 2 },
    ],
  },
  {
    type: 'Container',
    displayName: 'Container',
    category: 'Layout',
    icon: 'WebAsset',
    isContainer: true,
    defaultProps: { maxWidth: 'lg', fixed: false },
    defaultSx: { p: 2 },
    defaultSize: { width: 500, height: 300 },
    propSchema: [
      { name: 'maxWidth', label: 'Max Width', type: 'select', options: ['xs', 'sm', 'md', 'lg', 'xl', 'false'], defaultValue: 'lg' },
      { name: 'fixed', label: 'Fixed', type: 'boolean', defaultValue: false },
    ],
  },
];

/* Helper to look up a component's metadata */
export const getComponentMeta = (type: string): ComponentMeta | undefined =>
  componentRegistry.find((c) => c.type === type);

/* Unique list of categories in registry order */
export const registryCategories: ComponentCategory[] = categories;
