// ============================================================
// Component Registry â€” ALL MUI components, schema-driven
// ============================================================
import type { ComponentMeta, ComponentCategory } from '../../store/types';

export const categories: ComponentCategory[] = [
  'Inputs',
  'Data Display',
  'Surfaces',
  'Navigation',
  'Feedback',
  'Layout',
];

export const componentRegistry: ComponentMeta[] = [
  // â”€â”€ Inputs â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    type: 'Button',
    displayName: 'Button',
    category: 'Inputs',
    icon: 'SmartButton',
    isContainer: false,
    defaultProps: { label: 'Button', variant: 'contained', color: 'primary', size: 'medium', disabled: false },
    defaultSx: {},
    defaultSize: { width: 120, height: 40 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Button' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['contained', 'outlined', 'text'], defaultValue: 'contained' },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'success', 'error', 'warning', 'info', 'inherit'], defaultValue: 'primary' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'medium', 'large'], defaultValue: 'medium' },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'IconButton',
    displayName: 'Icon Button',
    category: 'Inputs',
    icon: 'TouchApp',
    isContainer: false,
    defaultProps: { color: 'primary', size: 'medium', disabled: false },
    defaultSx: {},
    defaultSize: { width: 48, height: 48 },
    propSchema: [
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'default', 'inherit'], defaultValue: 'primary' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'medium', 'large'], defaultValue: 'medium' },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'ButtonGroup',
    displayName: 'Button Group',
    category: 'Inputs',
    icon: 'ViewStream',
    isContainer: false,
    defaultProps: { buttons: ['One', 'Two', 'Three'], variant: 'outlined', color: 'primary' },
    defaultSx: {},
    defaultSize: { width: 260, height: 40 },
    propSchema: [
      { name: 'buttons', label: 'Buttons', type: 'list', defaultValue: ['One', 'Two', 'Three'] },
      { name: 'variant', label: 'Variant', type: 'select', options: ['contained', 'outlined', 'text'], defaultValue: 'outlined' },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'inherit'], defaultValue: 'primary' },
    ],
  },
  {
    type: 'TextField',
    displayName: 'Text Field',
    category: 'Inputs',
    icon: 'TextFields',
    isContainer: false,
    defaultProps: { label: 'Label', placeholder: 'Enter textâ€¦', variant: 'outlined', size: 'small', disabled: false, fullWidth: true },
    defaultSx: {},
    defaultSize: { width: 240, height: 56 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Label' },
      { name: 'placeholder', label: 'Placeholder', type: 'text', defaultValue: 'Enter textâ€¦' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['outlined', 'filled', 'standard'], defaultValue: 'outlined' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'medium'], defaultValue: 'small' },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
      { name: 'fullWidth', label: 'Full Width', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'Select',
    displayName: 'Select',
    category: 'Inputs',
    icon: 'ArrowDropDownCircle',
    isContainer: false,
    defaultProps: { label: 'Select', options: ['Option 1', 'Option 2', 'Option 3'] },
    defaultSx: {},
    defaultSize: { width: 240, height: 56 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Select' },
      { name: 'options', label: 'Options', type: 'list', defaultValue: ['Option 1', 'Option 2', 'Option 3'] },
    ],
  },
  {
    type: 'Checkbox',
    displayName: 'Checkbox',
    category: 'Inputs',
    icon: 'CheckBox',
    isContainer: false,
    defaultProps: { label: 'Check me', checked: false, disabled: false, color: 'primary' },
    defaultSx: {},
    defaultSize: { width: 180, height: 42 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Check me' },
      { name: 'checked', label: 'Checked', type: 'boolean', defaultValue: false },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'default'], defaultValue: 'primary' },
    ],
  },
  {
    type: 'Radio',
    displayName: 'Radio Group',
    category: 'Inputs',
    icon: 'RadioButtonChecked',
    isContainer: false,
    defaultProps: { label: 'Options', options: ['Option A', 'Option B', 'Option C'], row: false },
    defaultSx: {},
    defaultSize: { width: 200, height: 130 },
    propSchema: [
      { name: 'label', label: 'Group Label', type: 'text', defaultValue: 'Options' },
      { name: 'options', label: 'Options', type: 'list', defaultValue: ['Option A', 'Option B', 'Option C'] },
      { name: 'row', label: 'Row Layout', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Switch',
    displayName: 'Switch',
    category: 'Inputs',
    icon: 'ToggleOn',
    isContainer: false,
    defaultProps: { label: 'Toggle me', checked: false, disabled: false, color: 'primary' },
    defaultSx: {},
    defaultSize: { width: 180, height: 42 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Toggle me' },
      { name: 'checked', label: 'Checked', type: 'boolean', defaultValue: false },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'default'], defaultValue: 'primary' },
    ],
  },
  {
    type: 'Slider',
    displayName: 'Slider',
    category: 'Inputs',
    icon: 'LinearScale',
    isContainer: false,
    defaultProps: { value: 50, min: 0, max: 100, step: 1, disabled: false, color: 'primary' },
    defaultSx: {},
    defaultSize: { width: 240, height: 44 },
    propSchema: [
      { name: 'value', label: 'Value', type: 'number', defaultValue: 50 },
      { name: 'min', label: 'Min', type: 'number', defaultValue: 0 },
      { name: 'max', label: 'Max', type: 'number', defaultValue: 100 },
      { name: 'step', label: 'Step', type: 'number', defaultValue: 1 },
      { name: 'disabled', label: 'Disabled', type: 'boolean', defaultValue: false },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success'], defaultValue: 'primary' },
    ],
  },
  {
    type: 'Rating',
    displayName: 'Rating',
    category: 'Inputs',
    icon: 'StarRate',
    isContainer: false,
    defaultProps: { value: 3, max: 5, precision: 1, readOnly: false, disabled: false, size: 'medium' },
    defaultSx: {},
    defaultSize: { width: 200, height: 40 },
    propSchema: [
      { name: 'value', label: 'Value', type: 'number', defaultValue: 3 },
      { name: 'max', label: 'Max', type: 'number', defaultValue: 5 },
      { name: 'precision', label: 'Precision', type: 'select', options: ['0.5', '1'], defaultValue: 1 },
      { name: 'readOnly', label: 'Read Only', type: 'boolean', defaultValue: false },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'medium', 'large'], defaultValue: 'medium' },
    ],
  },
  {
    type: 'Autocomplete',
    displayName: 'Autocomplete',
    category: 'Inputs',
    icon: 'ManageSearch',
    isContainer: false,
    defaultProps: { label: 'Autocomplete', options: ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry'] },
    defaultSx: {},
    defaultSize: { width: 260, height: 56 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Autocomplete' },
      { name: 'options', label: 'Options', type: 'list', defaultValue: ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry'] },
    ],
  },
  {
    type: 'Fab',
    displayName: 'FAB',
    category: 'Inputs',
    icon: 'Add',
    isContainer: false,
    defaultProps: { color: 'primary', size: 'medium', variant: 'circular' },
    defaultSx: {},
    defaultSize: { width: 56, height: 56 },
    propSchema: [
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'inherit'], defaultValue: 'primary' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'medium', 'large'], defaultValue: 'medium' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['circular', 'extended'], defaultValue: 'circular' },
    ],
  },

  // â”€â”€ Data Display â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    type: 'Typography',
    displayName: 'Typography',
    category: 'Data Display',
    icon: 'Title',
    isContainer: false,
    defaultProps: { text: 'Typography Text', variant: 'body1', color: 'text.primary', align: 'left', gutterBottom: false },
    defaultSx: {},
    defaultSize: { width: 260, height: 32 },
    propSchema: [
      { name: 'text', label: 'Text', type: 'text', defaultValue: 'Typography Text' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'subtitle1', 'subtitle2', 'body1', 'body2', 'caption', 'overline'], defaultValue: 'body1' },
      { name: 'color', label: 'Color', type: 'select', options: ['text.primary', 'text.secondary', 'text.disabled', 'primary.main', 'secondary.main', 'error.main', 'warning.main', 'info.main', 'success.main'], defaultValue: 'text.primary' },
      { name: 'align', label: 'Align', type: 'select', options: ['left', 'center', 'right', 'justify'], defaultValue: 'left' },
      { name: 'gutterBottom', label: 'Gutter Bottom', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Avatar',
    displayName: 'Avatar',
    category: 'Data Display',
    icon: 'AccountCircle',
    isContainer: false,
    defaultProps: { text: 'AB', variant: 'circular', bgColor: '#1976d2' },
    defaultSx: {},
    defaultSize: { width: 48, height: 48 },
    propSchema: [
      { name: 'text', label: 'Initials', type: 'text', defaultValue: 'AB' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['circular', 'rounded', 'square'], defaultValue: 'circular' },
      { name: 'bgColor', label: 'Background', type: 'color', defaultValue: '#1976d2' },
    ],
  },
  {
    type: 'Badge',
    displayName: 'Badge',
    category: 'Data Display',
    icon: 'NotificationsActive',
    isContainer: false,
    defaultProps: { badgeContent: '4', color: 'error', variant: 'standard' },
    defaultSx: {},
    defaultSize: { width: 52, height: 52 },
    propSchema: [
      { name: 'badgeContent', label: 'Content', type: 'text', defaultValue: '4' },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'default'], defaultValue: 'error' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['standard', 'dot'], defaultValue: 'standard' },
    ],
  },
  {
    type: 'Chip',
    displayName: 'Chip',
    category: 'Data Display',
    icon: 'Label',
    isContainer: false,
    defaultProps: { label: 'Chip', variant: 'filled', color: 'primary', size: 'medium', clickable: false, deletable: false },
    defaultSx: {},
    defaultSize: { width: 100, height: 32 },
    propSchema: [
      { name: 'label', label: 'Label', type: 'text', defaultValue: 'Chip' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['filled', 'outlined'], defaultValue: 'filled' },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'default'], defaultValue: 'primary' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'medium'], defaultValue: 'medium' },
      { name: 'clickable', label: 'Clickable', type: 'boolean', defaultValue: false },
      { name: 'deletable', label: 'Deletable', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Divider',
    displayName: 'Divider',
    category: 'Data Display',
    icon: 'HorizontalRule',
    isContainer: false,
    defaultProps: { orientation: 'horizontal', variant: 'fullWidth', textAlign: 'center', text: '' },
    defaultSx: {},
    defaultSize: { width: 300, height: 20 },
    propSchema: [
      { name: 'orientation', label: 'Orientation', type: 'select', options: ['horizontal', 'vertical'], defaultValue: 'horizontal' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['fullWidth', 'inset', 'middle'], defaultValue: 'fullWidth' },
      { name: 'text', label: 'Text', type: 'text', defaultValue: '' },
    ],
  },
  {
    type: 'List',
    displayName: 'List',
    category: 'Data Display',
    icon: 'FormatListBulleted',
    isContainer: false,
    defaultProps: { items: ['Item 1', 'Item 2', 'Item 3'], dense: false },
    defaultSx: {},
    defaultSize: { width: 280, height: 160 },
    propSchema: [
      { name: 'items', label: 'Items', type: 'list', defaultValue: ['Item 1', 'Item 2', 'Item 3'] },
      { name: 'dense', label: 'Dense', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Table',
    displayName: 'Table',
    category: 'Data Display',
    icon: 'TableChart',
    isContainer: false,
    defaultProps: { columns: ['#', 'Name', 'Email', 'Role'], rows: ['1,Alice,alice@mail.com,Admin', '2,Bob,bob@mail.com,User'], stickyHeader: false, size: 'medium' },
    defaultSx: {},
    defaultSize: { width: 420, height: 220 },
    propSchema: [
      { name: 'columns', label: 'Columns', type: 'list', defaultValue: ['#', 'Name', 'Email', 'Role'] },
      { name: 'rows', label: 'Rows (comma-separated)', type: 'list', defaultValue: ['1,Alice,alice@mail.com,Admin', '2,Bob,bob@mail.com,User'] },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'medium'], defaultValue: 'medium' },
      { name: 'stickyHeader', label: 'Sticky Header', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'Tooltip',
    displayName: 'Tooltip',
    category: 'Data Display',
    icon: 'Info',
    isContainer: false,
    defaultProps: { title: 'Tooltip text', placement: 'top', arrow: true },
    defaultSx: {},
    defaultSize: { width: 120, height: 40 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Tooltip text' },
      { name: 'placement', label: 'Placement', type: 'select', options: ['top', 'bottom', 'left', 'right'], defaultValue: 'top' },
      { name: 'arrow', label: 'Arrow', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'Image',
    displayName: 'Image',
    category: 'Data Display',
    icon: 'Image',
    isContainer: false,
    defaultProps: { src: 'https://via.placeholder.com/300x200', alt: 'placeholder', objectFit: 'cover' },
    defaultSx: {},
    defaultSize: { width: 300, height: 200 },
    propSchema: [
      { name: 'src', label: 'Source URL', type: 'text', defaultValue: 'https://via.placeholder.com/300x200' },
      { name: 'alt', label: 'Alt Text', type: 'text', defaultValue: 'placeholder' },
      { name: 'objectFit', label: 'Object Fit', type: 'select', options: ['cover', 'contain', 'fill', 'none'], defaultValue: 'cover' },
    ],
  },

  // â”€â”€ Surfaces â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    type: 'Card',
    displayName: 'Card',
    category: 'Surfaces',
    icon: 'CreditCard',
    isContainer: true,
    defaultProps: { elevation: 1, title: 'Card Title', content: 'Card content goes here.' },
    defaultSx: {},
    defaultSize: { width: 320, height: 180 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Card Title' },
      { name: 'content', label: 'Content', type: 'text', defaultValue: 'Card content goes here.' },
      { name: 'elevation', label: 'Elevation', type: 'slider', defaultValue: 1, min: 0, max: 24, step: 1 },
    ],
  },
  {
    type: 'Paper',
    displayName: 'Paper',
    category: 'Surfaces',
    icon: 'Description',
    isContainer: true,
    defaultProps: { elevation: 1, square: false, variant: 'elevation' },
    defaultSx: { p: 2 },
    defaultSize: { width: 300, height: 200 },
    propSchema: [
      { name: 'elevation', label: 'Elevation', type: 'slider', defaultValue: 1, min: 0, max: 24, step: 1 },
      { name: 'square', label: 'Square', type: 'boolean', defaultValue: false },
      { name: 'variant', label: 'Variant', type: 'select', options: ['elevation', 'outlined'], defaultValue: 'elevation' },
    ],
  },
  {
    type: 'Accordion',
    displayName: 'Accordion',
    category: 'Surfaces',
    icon: 'ExpandMore',
    isContainer: false,
    defaultProps: { title: 'Accordion', content: 'Accordion content goes here.', defaultExpanded: false },
    defaultSx: {},
    defaultSize: { width: 320, height: 56 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Accordion' },
      { name: 'content', label: 'Content', type: 'text', defaultValue: 'Accordion content goes here.' },
      { name: 'defaultExpanded', label: 'Default Expanded', type: 'boolean', defaultValue: false },
    ],
  },

  // -- Navigation ---------------------------------------------------
  {
    type: 'AppBar',
    displayName: 'App Bar',
    category: 'Navigation',
    icon: 'WebAsset',
    isContainer: false,
    defaultProps: { title: 'App Title', color: 'primary', position: 'static', actions: ['Login'] },
    defaultSx: {},
    defaultSize: { width: 400, height: 64 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'App Title' },
      { name: 'actions', label: 'Actions', type: 'list', defaultValue: ['Login'] },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'default', 'transparent', 'inherit'], defaultValue: 'primary' },
    ],
  },
  {
    type: 'Tabs',
    displayName: 'Tabs',
    category: 'Navigation',
    icon: 'Tab',
    isContainer: false,
    defaultProps: { tabs: ['Tab 1', 'Tab 2', 'Tab 3'], variant: 'standard', color: 'primary' },
    defaultSx: {},
    defaultSize: { width: 360, height: 48 },
    propSchema: [
      { name: 'tabs', label: 'Tabs', type: 'list', defaultValue: ['Tab 1', 'Tab 2', 'Tab 3'] },
      { name: 'variant', label: 'Variant', type: 'select', options: ['standard', 'scrollable', 'fullWidth'], defaultValue: 'standard' },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary'], defaultValue: 'primary' },
    ],
  },
  {
    type: 'Breadcrumbs',
    displayName: 'Breadcrumbs',
    category: 'Navigation',
    icon: 'ChevronRight',
    isContainer: false,
    defaultProps: { items: ['Home', 'Category', 'Current'] },
    defaultSx: {},
    defaultSize: { width: 280, height: 32 },
    propSchema: [
      { name: 'items', label: 'Items', type: 'list', defaultValue: ['Home', 'Category', 'Current'] },
    ],
  },
  {
    type: 'Drawer',
    displayName: 'Drawer',
    category: 'Navigation',
    icon: 'Menu',
    isContainer: false,
    defaultProps: { anchor: 'left', width: 240, menuItems: ['Dashboard', 'Settings > Profile', 'Settings > Account', 'Settings > Privacy', 'Reports'], title: 'Drawer' },
    defaultSx: {},
    defaultSize: { width: 240, height: 400 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Drawer' },
      { name: 'menuItems', label: 'Menu Items', type: 'list', defaultValue: ['Dashboard', 'Settings > Profile', 'Settings > Account', 'Settings > Privacy', 'Reports'] },
      { name: 'anchor', label: 'Anchor', type: 'select', options: ['left', 'right', 'top', 'bottom'], defaultValue: 'left' },
      { name: 'width', label: 'Width', type: 'number', defaultValue: 240 },
    ],
  },
  {
    type: 'Pagination',
    displayName: 'Pagination',
    category: 'Navigation',
    icon: 'MoreHoriz',
    isContainer: false,
    defaultProps: { count: 10, color: 'primary', shape: 'rounded', variant: 'outlined', size: 'medium' },
    defaultSx: {},
    defaultSize: { width: 320, height: 40 },
    propSchema: [
      { name: 'count', label: 'Pages', type: 'number', defaultValue: 10 },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'standard'], defaultValue: 'primary' },
      { name: 'shape', label: 'Shape', type: 'select', options: ['rounded', 'circular'], defaultValue: 'rounded' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['text', 'outlined'], defaultValue: 'outlined' },
      { name: 'size', label: 'Size', type: 'select', options: ['small', 'medium', 'large'], defaultValue: 'medium' },
    ],
  },
  {
    type: 'Stepper',
    displayName: 'Stepper',
    category: 'Navigation',
    icon: 'LinearScale',
    isContainer: false,
    defaultProps: { steps: ['Step 1', 'Step 2', 'Step 3'], activeStep: 0, orientation: 'horizontal' },
    defaultSx: {},
    defaultSize: { width: 400, height: 72 },
    propSchema: [
      { name: 'steps', label: 'Steps', type: 'list', defaultValue: ['Step 1', 'Step 2', 'Step 3'] },
      { name: 'activeStep', label: 'Active Step', type: 'number', defaultValue: 0 },
      { name: 'orientation', label: 'Orientation', type: 'select', options: ['horizontal', 'vertical'], defaultValue: 'horizontal' },
    ],
  },
  {
    type: 'BottomNavigation',
    displayName: 'Bottom Nav',
    category: 'Navigation',
    icon: 'VerticalAlignBottom',
    isContainer: false,
    defaultProps: { items: ['Recents', 'Favorites', 'Nearby'], showLabels: true },
    defaultSx: {},
    defaultSize: { width: 360, height: 56 },
    propSchema: [
      { name: 'items', label: 'Items', type: 'list', defaultValue: ['Recents', 'Favorites', 'Nearby'] },
      { name: 'showLabels', label: 'Show Labels', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'SpeedDial',
    displayName: 'Speed Dial',
    category: 'Navigation',
    icon: 'Speed',
    isContainer: false,
    defaultProps: { direction: 'up', actions: ['Edit', 'Share', 'Print'] },
    defaultSx: {},
    defaultSize: { width: 56, height: 56 },
    propSchema: [
      { name: 'actions', label: 'Actions', type: 'list', defaultValue: ['Edit', 'Share', 'Print'] },
      { name: 'direction', label: 'Direction', type: 'select', options: ['up', 'down', 'left', 'right'], defaultValue: 'up' },
    ],
  },

  // ── Feedback ─────────────────────────────────────────────
  {
    type: 'Alert',
    displayName: 'Alert',
    category: 'Feedback',
    icon: 'Warning',
    isContainer: false,
    defaultProps: { severity: 'info', text: 'This is an alert.', variant: 'standard' },
    defaultSx: {},
    defaultSize: { width: 320, height: 48 },
    propSchema: [
      { name: 'text', label: 'Text', type: 'text', defaultValue: 'This is an alert.' },
      { name: 'severity', label: 'Severity', type: 'select', options: ['error', 'warning', 'info', 'success'], defaultValue: 'info' },
      { name: 'variant', label: 'Variant', type: 'select', options: ['standard', 'filled', 'outlined'], defaultValue: 'standard' },
    ],
  },
  {
    type: 'Snackbar',
    displayName: 'Snackbar',
    category: 'Feedback',
    icon: 'Announcement',
    isContainer: false,
    defaultProps: { message: 'Snackbar message', anchorVertical: 'bottom', anchorHorizontal: 'left' },
    defaultSx: {},
    defaultSize: { width: 320, height: 48 },
    propSchema: [
      { name: 'message', label: 'Message', type: 'text', defaultValue: 'Snackbar message' },
      { name: 'anchorVertical', label: 'Vertical', type: 'select', options: ['top', 'bottom'], defaultValue: 'bottom' },
      { name: 'anchorHorizontal', label: 'Horizontal', type: 'select', options: ['left', 'center', 'right'], defaultValue: 'left' },
    ],
  },
  {
    type: 'Dialog',
    displayName: 'Dialog',
    category: 'Feedback',
    icon: 'OpenInNew',
    isContainer: false,
    defaultProps: { title: 'Dialog Title', content: 'Dialog content text.', maxWidth: 'sm', actions: ['Cancel', 'OK'] },
    defaultSx: {},
    defaultSize: { width: 400, height: 200 },
    propSchema: [
      { name: 'title', label: 'Title', type: 'text', defaultValue: 'Dialog Title' },
      { name: 'content', label: 'Content', type: 'text', defaultValue: 'Dialog content text.' },
      { name: 'actions', label: 'Actions', type: 'list', defaultValue: ['Cancel', 'OK'] },
      { name: 'maxWidth', label: 'Max Width', type: 'select', options: ['xs', 'sm', 'md', 'lg', 'xl'], defaultValue: 'sm' },
    ],
  },
  {
    type: 'CircularProgress',
    displayName: 'Circular Progress',
    category: 'Feedback',
    icon: 'Refresh',
    isContainer: false,
    defaultProps: { variant: 'indeterminate', color: 'primary', size: 40, value: 50 },
    defaultSx: {},
    defaultSize: { width: 48, height: 48 },
    propSchema: [
      { name: 'variant', label: 'Variant', type: 'select', options: ['determinate', 'indeterminate'], defaultValue: 'indeterminate' },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'inherit'], defaultValue: 'primary' },
      { name: 'size', label: 'Size', type: 'number', defaultValue: 40 },
      { name: 'value', label: 'Value', type: 'slider', defaultValue: 50, min: 0, max: 100, step: 1 },
    ],
  },
  {
    type: 'LinearProgress',
    displayName: 'Linear Progress',
    category: 'Feedback',
    icon: 'HorizontalRule',
    isContainer: false,
    defaultProps: { variant: 'indeterminate', color: 'primary', value: 50 },
    defaultSx: {},
    defaultSize: { width: 300, height: 8 },
    propSchema: [
      { name: 'variant', label: 'Variant', type: 'select', options: ['determinate', 'indeterminate', 'buffer', 'query'], defaultValue: 'indeterminate' },
      { name: 'color', label: 'Color', type: 'select', options: ['primary', 'secondary', 'error', 'warning', 'info', 'success', 'inherit'], defaultValue: 'primary' },
      { name: 'value', label: 'Value', type: 'slider', defaultValue: 50, min: 0, max: 100, step: 1 },
    ],
  },
  {
    type: 'Skeleton',
    displayName: 'Skeleton',
    category: 'Feedback',
    icon: 'Crop169',
    isContainer: false,
    defaultProps: { variant: 'rectangular', animation: 'pulse' },
    defaultSx: {},
    defaultSize: { width: 240, height: 60 },
    propSchema: [
      { name: 'variant', label: 'Variant', type: 'select', options: ['text', 'circular', 'rectangular', 'rounded'], defaultValue: 'rectangular' },
      { name: 'animation', label: 'Animation', type: 'select', options: ['pulse', 'wave', 'false'], defaultValue: 'pulse' },
    ],
  },

  // -- Layout -------------------------------------------------------
  {
    type: 'Box',
    displayName: 'Box',
    category: 'Layout',
    icon: 'CheckBoxOutlineBlank',
    isContainer: true,
    defaultProps: {},
    defaultSx: { p: 2, border: '1px dashed grey' },
    defaultSize: { width: 300, height: 200 },
    propSchema: [],
  },
  {
    type: 'Stack',
    displayName: 'Stack',
    category: 'Layout',
    icon: 'ViewAgenda',
    isContainer: true,
    defaultProps: { direction: 'column', spacing: 2, alignItems: 'stretch', justifyContent: 'flex-start' },
    defaultSx: { p: 1 },
    defaultSize: { width: 300, height: 200 },
    propSchema: [
      { name: 'direction', label: 'Direction', type: 'select', options: ['row', 'column', 'row-reverse', 'column-reverse'], defaultValue: 'column' },
      { name: 'spacing', label: 'Spacing', type: 'number', defaultValue: 2 },
      { name: 'alignItems', label: 'Align Items', type: 'select', options: ['flex-start', 'center', 'flex-end', 'stretch', 'baseline'], defaultValue: 'stretch' },
      { name: 'justifyContent', label: 'Justify', type: 'select', options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around', 'space-evenly'], defaultValue: 'flex-start' },
    ],
  },
  {
    type: 'Grid',
    displayName: 'Grid',
    category: 'Layout',
    icon: 'GridView',
    isContainer: true,
    defaultProps: { columns: 12, cols: 3, spacing: 2 },
    defaultSx: {},
    defaultSize: { width: 400, height: 200 },
    propSchema: [
      { name: 'cols', label: 'Columns', type: 'select', options: ['1', '2', '3', '4', '6'], defaultValue: '3' },
      { name: 'spacing', label: 'Spacing', type: 'number', defaultValue: 2 },
    ],
  },
  {
    type: 'Container',
    displayName: 'Container',
    category: 'Layout',
    icon: 'WebAsset',
    isContainer: true,
    defaultProps: { maxWidth: 'lg', fixed: false },
    defaultSx: { p: 2 },
    defaultSize: { width: 500, height: 300 },
    propSchema: [
      { name: 'maxWidth', label: 'Max Width', type: 'select', options: ['xs', 'sm', 'md', 'lg', 'xl', 'false'], defaultValue: 'lg' },
      { name: 'fixed', label: 'Fixed', type: 'boolean', defaultValue: false },
    ],
  },
];

/* Helper to look up a component's metadata */
export const getComponentMeta = (type: string): ComponentMeta | undefined =>
  componentRegistry.find((c) => c.type === type);

/* Unique list of categories in registry order */
export const registryCategories: ComponentCategory[] = categories;
