// ============================================================
// Smart Code Generator — Layout tree → production React code
// ============================================================
import type { LayoutNode } from '../store/types';
import { buildClassString } from '../utils/icgClassBuilder';

/** Generate complete React component code from layout tree. */
export const generateCode = (layoutTree: LayoutNode[], designName: string): string => {
  const collector = new ImportCollector();
  const stateHooks: string[] = [];
  const dataDeclarations: string[] = [];

  // First pass: collect imports, state hooks, data
  walkForMeta(layoutTree, collector, stateHooks, dataDeclarations);

  // Second pass: generate JSX
  const jsx = layoutTree.map((node) => generateNodeJSX(node, '    ', collector)).join('\n');

  // Build component name
  const componentName = designName
    ? designName.replace(/[^a-zA-Z0-9]/g, '').replace(/^[^A-Z]/i, (c) => c.toUpperCase()) || 'GeneratedPage'
    : 'GeneratedPage';

  const imports = collector.getImportStatement();
  const stateCode = stateHooks.length > 0 ? '\n  ' + stateHooks.join('\n  ') + '\n' : '';
  const dataCode = dataDeclarations.length > 0 ? '\n  ' + dataDeclarations.join('\n\n  ') + '\n' : '';

  // ThemeProvider import
  const themeProviderImport = `import { ThemeProvider } from '@citi-icg-172888/icgds-react';`;

  return `// Auto-generated by ICG Layout Builder
// Design: "${designName || 'Untitled'}"
// Date: ${new Date().toISOString().split('T')[0]}

import React${stateHooks.length > 0 ? ', { useState }' : ''} from 'react';
${themeProviderImport}
${imports}

const ${componentName}: React.FC = () => {${stateCode}${dataCode}
  return (
    <ThemeProvider>
${jsx}
    </ThemeProvider>
  );
};

export default ${componentName};
`;
};

/* ─── Import Collector ────────────────────────────────── */
class ImportCollector {
  private _imports = new Set<string>();

  add(componentName: string): void {
    this._imports.add(componentName);
  }

  getImportStatement(): string {
    if (this._imports.size === 0) return '';
    const sorted = [...this._imports].sort();
    return `import { ${sorted.join(', ')} } from '@citi-icg-172888/icgds-react';`;
  }
}

/* ─── Meta walk (collect imports, hooks, data) ────────── */
function walkForMeta(
  nodes: LayoutNode[],
  collector: ImportCollector,
  stateHooks: string[],
  dataDeclarations: string[],
): void {
  for (const node of nodes) {
    if (node.type === 'component' && node.componentType) {
      const strategy = getStrategy(node.componentType);
      if (strategy) {
        strategy.collectImports(node, collector);
        strategy.collectState?.(node, stateHooks);
        strategy.collectData?.(node, dataDeclarations);
      }
    }
    walkForMeta(node.children, collector, stateHooks, dataDeclarations);
  }
}

/* ─── JSX Generation ──────────────────────────────────── */
function generateNodeJSX(node: LayoutNode, indent: string, collector: ImportCollector): string {
  switch (node.type) {
    case 'container':
      return generateContainerJSX(node, indent, collector);
    case 'row':
      return generateRowJSX(node, indent, collector);
    case 'column':
      return generateColumnJSX(node, indent, collector);
    case 'flex-container':
      return generateFlexJSX(node, indent, collector);
    case 'content':
      return generateContentJSX(node, indent);
    case 'component':
      return generateComponentJSX(node, indent, collector);
    default:
      return '';
  }
}

function generateContainerJSX(node: LayoutNode, indent: string, collector: ImportCollector): string {
  const cls = node.props.fluid ? 'lmn-container-fluid' : 'lmn-container';
  const extra = node.icgClasses.filter((c) => c !== 'lmn-container' && c !== 'lmn-container-fluid');
  const className = buildClassString(cls, ...extra);
  const children = node.children.map((c) => generateNodeJSX(c, indent + '  ', collector)).join('\n');
  return `${indent}<div className="${className}">\n${children}\n${indent}</div>`;
}

function generateRowJSX(node: LayoutNode, indent: string, collector: ImportCollector): string {
  const className = buildClassString(...node.icgClasses);
  const children = node.children.map((c) => generateNodeJSX(c, indent + '  ', collector)).join('\n');
  return `${indent}<div className="${className}">\n${children}\n${indent}</div>`;
}

function generateColumnJSX(node: LayoutNode, indent: string, collector: ImportCollector): string {
  const className = buildClassString(...node.icgClasses);
  const children = node.children.map((c) => generateNodeJSX(c, indent + '  ', collector)).join('\n');
  return `${indent}<div className="${className}">\n${children}\n${indent}</div>`;
}

function generateFlexJSX(node: LayoutNode, indent: string, collector: ImportCollector): string {
  const className = buildClassString(...node.icgClasses);
  const children = node.children.map((c) => generateNodeJSX(c, indent + '  ', collector)).join('\n');
  return `${indent}<div className="${className}">\n${children}\n${indent}</div>`;
}

function generateContentJSX(node: LayoutNode, indent: string): string {
  const text = String(node.props.text ?? '');
  const align = node.props.align as string | undefined;
  const alignClass = align ? `lmn-text-${align}` : '';

  switch (node.contentType) {
    case 'heading': {
      const level = (node.props.level as string) ?? 'h2';
      const colorClass = (node.props.colorClass as string) ?? '';
      const variant = node.props.variant as string;
      const variantClass = variant === 'compact' ? 'lmn-ui-compact' : variant === 'spacious' ? 'lmn-ui-spacious' : '';
      const cls = buildClassString(`lmn-${level}`, colorClass, alignClass, variantClass, ...node.icgClasses);
      return `${indent}<${level} className="${cls}">${escapeJSX(text)}</${level}>`;
    }
    case 'display-heading': {
      const size = (node.props.size as string) ?? '1';
      const cls = buildClassString(`lmn-display-${size}`, alignClass, ...node.icgClasses);
      return `${indent}<h1 className="${cls}">${escapeJSX(text)}</h1>`;
    }
    case 'paragraph': {
      const colorClass = (node.props.colorClass as string) ?? '';
      const weight = node.props.fontWeight as string;
      const weightClass = weight && weight !== 'regular' ? `lmn-font-weight-${weight}` : '';
      const cls = buildClassString(colorClass, alignClass, weightClass, ...node.icgClasses);
      return `${indent}<p className="${cls}">${escapeJSX(text)}</p>`;
    }
    case 'lead': {
      const cls = buildClassString('lmn-lead', alignClass, ...node.icgClasses);
      return `${indent}<p className="${cls}">${escapeJSX(text)}</p>`;
    }
    default:
      return '';
  }
}

function generateComponentJSX(node: LayoutNode, indent: string, collector: ImportCollector): string {
  const strategy = getStrategy(node.componentType ?? '');
  if (strategy) {
    return strategy.generateJSX(node, indent);
  }
  // Fallback: generic component rendering
  const compType = node.componentType ?? 'Unknown';
  collector.add(compType);
  const propsStr = generatePropsString(node.props, ['label', 'text', 'message', 'content', 'items', 'options', 'columns', 'rows', 'steps', 'tabs', 'slides']);
  const classAttr = node.icgClasses.length > 0 ? ` className="${buildClassString(...node.icgClasses)}"` : '';
  const textChild = node.props.label || node.props.text || '';
  if (textChild) {
    return `${indent}<${compType}${propsStr}${classAttr}>${escapeJSX(String(textChild))}</${compType}>`;
  }
  return `${indent}<${compType}${propsStr}${classAttr} />`;
}

/* ─── Per-Component Strategies ────────────────────────── */
interface ComponentStrategy {
  collectImports: (node: LayoutNode, collector: ImportCollector) => void;
  collectState?: (node: LayoutNode, hooks: string[]) => void;
  collectData?: (node: LayoutNode, declarations: string[]) => void;
  generateJSX: (node: LayoutNode, indent: string) => string;
}

const strategies: Record<string, ComponentStrategy> = {
  button: {
    collectImports: (_n, c) => c.add('Button'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.type && p.type !== 'default') attrs.push(`type="${p.type}"`);
      if (p.size && p.size !== 'middle') attrs.push(`size="${p.size}"`);
      if (p.danger) attrs.push('danger');
      if (p.disabled) attrs.push('disabled');
      if (p.block) attrs.push('block');
      if (p.shape && p.shape !== 'default') attrs.push(`shape="${p.shape}"`);
      const attrStr = attrs.length > 0 ? ' ' + attrs.join(' ') : '';
      return `${indent}<Button${attrStr}>${escapeJSX(String(p.label ?? 'Button'))}</Button>`;
    },
  },

  input: {
    collectImports: (_n, c) => c.add('Input'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.placeholder) attrs.push(`placeholder="${p.placeholder}"`);
      if (p.size && p.size !== 'middle') attrs.push(`size="${p.size}"`);
      if (p.disabled) attrs.push('disabled');
      if (p.allowClear) attrs.push('allowClear');
      return `${indent}<Input ${attrs.join(' ')} />`;
    },
  },

  inputTextArea: {
    collectImports: (_n, c) => c.add('Input'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.placeholder) attrs.push(`placeholder="${p.placeholder}"`);
      if (p.rows) attrs.push(`rows={${p.rows}}`);
      if (p.disabled) attrs.push('disabled');
      return `${indent}<Input.TextArea ${attrs.join(' ')} />`;
    },
  },

  inputNumber: {
    collectImports: (_n, c) => c.add('InputNumber'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.placeholder) attrs.push(`placeholder="${p.placeholder}"`);
      if (p.min !== undefined) attrs.push(`min={${p.min}}`);
      if (p.max !== undefined) attrs.push(`max={${p.max}}`);
      if (p.size && p.size !== 'middle') attrs.push(`size="${p.size}"`);
      if (p.disabled) attrs.push('disabled');
      return `${indent}<InputNumber ${attrs.join(' ')} />`;
    },
  },

  select: {
    collectImports: (_n, c) => c.add('Select'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const options = Array.isArray(p.options) ? p.options as string[] : [];
      const optionsCode = options.map((o) => `{ value: '${o}', label: '${o}' }`).join(', ');
      const attrs: string[] = [];
      if (p.placeholder) attrs.push(`placeholder="${p.placeholder}"`);
      attrs.push(`options={[${optionsCode}]}`);
      if (p.size && p.size !== 'middle') attrs.push(`size="${p.size}"`);
      if (p.disabled) attrs.push('disabled');
      if (p.allowClear) attrs.push('allowClear');
      if (p.showSearch) attrs.push('showSearch');
      return `${indent}<Select ${attrs.join(' ')} />`;
    },
  },

  checkbox: {
    collectImports: (_n, c) => c.add('Checkbox'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.disabled) attrs.push('disabled');
      return `${indent}<Checkbox${attrs.length ? ' ' + attrs.join(' ') : ''}>${escapeJSX(String(p.label ?? ''))}</Checkbox>`;
    },
  },

  radio: {
    collectImports: (_n, c) => { c.add('Radio'); },
    generateJSX: (node, indent) => {
      const p = node.props;
      const options = Array.isArray(p.options) ? p.options as string[] : [];
      const optionsCode = options.map((o) => `{ value: '${o}', label: '${o}' }`).join(', ');
      const attrs: string[] = [`options={[${optionsCode}]}`];
      if (p.optionType && p.optionType !== 'default') attrs.push(`optionType="${p.optionType}"`);
      if (p.buttonStyle && p.buttonStyle !== 'outline') attrs.push(`buttonStyle="${p.buttonStyle}"`);
      return `${indent}<Radio.Group ${attrs.join(' ')} />`;
    },
  },

  switch: {
    collectImports: (_n, c) => c.add('Switch'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.disabled) attrs.push('disabled');
      if (p.size && p.size !== 'default') attrs.push(`size="${p.size}"`);
      const label = p.label ? `<span>${escapeJSX(String(p.label))}</span> ` : '';
      return `${indent}${label}<Switch ${attrs.join(' ')} />`;
    },
  },

  slider: {
    collectImports: (_n, c) => c.add('Slider'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.min !== undefined) attrs.push(`min={${p.min}}`);
      if (p.max !== undefined) attrs.push(`max={${p.max}}`);
      if (p.step !== undefined && p.step !== 1) attrs.push(`step={${p.step}}`);
      if (p.disabled) attrs.push('disabled');
      if (p.value !== undefined) attrs.push(`defaultValue={${p.value}}`);
      return `${indent}<Slider ${attrs.join(' ')} />`;
    },
  },

  datePicker: {
    collectImports: (_n, c) => c.add('DatePicker'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.placeholder) attrs.push(`placeholder="${p.placeholder}"`);
      if (p.size && p.size !== 'middle') attrs.push(`size="${p.size}"`);
      if (p.picker && p.picker !== 'date') attrs.push(`picker="${p.picker}"`);
      if (p.disabled) attrs.push('disabled');
      return `${indent}<DatePicker ${attrs.join(' ')} />`;
    },
  },

  upload: {
    collectImports: (_n, c) => { c.add('Upload'); c.add('Button'); },
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.listType && p.listType !== 'text') attrs.push(`listType="${p.listType}"`);
      return `${indent}<Upload${attrs.length ? ' ' + attrs.join(' ') : ''}>
${indent}  <Button>${escapeJSX(String(p.text ?? 'Upload'))}</Button>
${indent}</Upload>`;
    },
  },

  avatar: {
    collectImports: (_n, c) => c.add('Avatar'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.shape && p.shape !== 'circle') attrs.push(`shape="${p.shape}"`);
      if (p.size && p.size !== 'default') attrs.push(`size="${p.size}"`);
      return `${indent}<Avatar ${attrs.join(' ')}>${escapeJSX(String(p.text ?? ''))}</Avatar>`;
    },
  },

  badge: {
    collectImports: (_n, c) => { c.add('Badge'); c.add('Avatar'); },
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.count !== undefined) attrs.push(`count={${p.count}}`);
      if (p.dot) attrs.push('dot');
      if (p.showZero) attrs.push('showZero');
      return `${indent}<Badge ${attrs.join(' ')}>
${indent}  <Avatar shape="square">U</Avatar>
${indent}</Badge>`;
    },
  },

  tag: {
    collectImports: (_n, c) => c.add('Tag'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.color && p.color !== 'default') attrs.push(`color="${p.color}"`);
      if (p.closable) attrs.push('closable');
      if (p.bordered === false) attrs.push('bordered={false}');
      return `${indent}<Tag ${attrs.join(' ')}>${escapeJSX(String(p.label ?? 'Tag'))}</Tag>`;
    },
  },

  divider: {
    collectImports: (_n, c) => c.add('Divider'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.type && p.type !== 'horizontal') attrs.push(`type="${p.type}"`);
      if (p.dashed) attrs.push('dashed');
      if (p.orientation && p.orientation !== 'center') attrs.push(`orientation="${p.orientation}"`);
      const text = p.text ? escapeJSX(String(p.text)) : '';
      if (text) return `${indent}<Divider ${attrs.join(' ')}>${text}</Divider>`;
      return `${indent}<Divider ${attrs.join(' ')} />`;
    },
  },

  list: {
    collectImports: (_n, c) => c.add('List'),
    collectData: (node, declarations) => {
      const items = Array.isArray(node.props.items) ? node.props.items as string[] : [];
      const varName = `listData_${node.id.slice(0, 6)}`;
      declarations.push(`const ${varName} = ${JSON.stringify(items)};`);
    },
    generateJSX: (node, indent) => {
      const p = node.props;
      const varName = `listData_${node.id.slice(0, 6)}`;
      const attrs: string[] = [`dataSource={${varName}}`];
      attrs.push(`renderItem={(item: string) => <List.Item>{item}</List.Item>}`);
      if (p.bordered) attrs.push('bordered');
      if (p.size && p.size !== 'default') attrs.push(`size="${p.size}"`);
      return `${indent}<List\n${indent}  ${attrs.join(`\n${indent}  `)}\n${indent}/>`;
    },
  },

  table: {
    collectImports: (_n, c) => c.add('Table'),
    collectData: (node, declarations) => {
      const cols = Array.isArray(node.props.columns) ? node.props.columns as string[] : [];
      const rows = Array.isArray(node.props.rows) ? node.props.rows as string[] : [];
      const colName = `columns_${node.id.slice(0, 6)}`;
      const dataName = `data_${node.id.slice(0, 6)}`;
      const colDefs = cols.map((c, i) => `  { title: '${c}', dataIndex: 'col${i}', key: 'col${i}' }`).join(',\n');
      declarations.push(`const ${colName} = [\n${colDefs}\n  ];`);
      const dataDefs = rows.map((r, ri) => {
        const vals = r.split(',');
        const obj = cols.map((_, ci) => `col${ci}: '${(vals[ci] ?? '').trim()}'`).join(', ');
        return `  { key: '${ri}', ${obj} }`;
      }).join(',\n');
      declarations.push(`const ${dataName} = [\n${dataDefs}\n  ];`);
    },
    generateJSX: (node, indent) => {
      const p = node.props;
      const colName = `columns_${node.id.slice(0, 6)}`;
      const dataName = `data_${node.id.slice(0, 6)}`;
      const attrs: string[] = [`columns={${colName}}`, `dataSource={${dataName}}`];
      if (p.size && p.size !== 'middle') attrs.push(`size="${p.size}"`);
      if (p.bordered) attrs.push('bordered');
      return `${indent}<Table ${attrs.join(' ')} />`;
    },
  },

  tooltip: {
    collectImports: (_n, c) => { c.add('Tooltip'); c.add('Button'); },
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [`title="${p.title ?? 'Tooltip'}"`];
      if (p.placement && p.placement !== 'top') attrs.push(`placement="${p.placement}"`);
      return `${indent}<Tooltip ${attrs.join(' ')}>
${indent}  <Button>Hover me</Button>
${indent}</Tooltip>`;
    },
  },

  image: {
    collectImports: (_n, c) => c.add('Image'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.src) attrs.push(`src="${p.src}"`);
      if (p.alt) attrs.push(`alt="${p.alt}"`);
      return `${indent}<Image ${attrs.join(' ')} />`;
    },
  },

  carousel: {
    collectImports: (_n, c) => c.add('Carousel'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const slides = Array.isArray(p.slides) ? p.slides as string[] : [];
      const attrs: string[] = [];
      if (p.autoplay) attrs.push('autoplay');
      if (p.dots === false) attrs.push('dots={false}');
      if (p.effect && p.effect !== 'scrollx') attrs.push(`effect="${p.effect}"`);
      const slideJSX = slides.map((s) => `${indent}  <div><h3>${escapeJSX(s)}</h3></div>`).join('\n');
      return `${indent}<Carousel ${attrs.join(' ')}>\n${slideJSX}\n${indent}</Carousel>`;
    },
  },

  card: {
    collectImports: (_n, c) => c.add('Card'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.title) attrs.push(`title="${p.title}"`);
      if (p.bordered === false) attrs.push('bordered={false}');
      if (p.hoverable) attrs.push('hoverable');
      if (p.size && p.size !== 'default') attrs.push(`size="${p.size}"`);
      return `${indent}<Card ${attrs.join(' ')}>
${indent}  <p>Card content</p>
${indent}</Card>`;
    },
  },

  section: {
    collectImports: (_n, c) => c.add('Section'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.title) attrs.push(`title="${p.title}"`);
      if (p.bordered === false) attrs.push('bordered={false}');
      return `${indent}<Section ${attrs.join(' ')}>
${indent}  <p>Section content</p>
${indent}</Section>`;
    },
  },

  collapse: {
    collectImports: (_n, c) => c.add('Collapse'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.bordered === false) attrs.push('bordered={false}');
      if (p.defaultExpanded) attrs.push('defaultActiveKey={["1"]}');
      return `${indent}<Collapse ${attrs.join(' ')}>
${indent}  <Collapse.Panel header="${escapeJSX(String(p.title ?? 'Panel'))}" key="1">
${indent}    <p>${escapeJSX(String(p.content ?? ''))}</p>
${indent}  </Collapse.Panel>
${indent}</Collapse>`;
    },
  },

  menu: {
    collectImports: (_n, c) => c.add('Menu'),
    collectData: (node, declarations) => {
      const items = Array.isArray(node.props.items) ? node.props.items as string[] : [];
      const varName = `menuItems_${node.id.slice(0, 6)}`;
      const itemsDef = items.map((it, i) => `  { key: '${i}', label: '${it}' }`).join(',\n');
      declarations.push(`const ${varName} = [\n${itemsDef}\n  ];`);
    },
    generateJSX: (node, indent) => {
      const p = node.props;
      const varName = `menuItems_${node.id.slice(0, 6)}`;
      const attrs: string[] = [`items={${varName}}`];
      if (p.mode && p.mode !== 'horizontal') attrs.push(`mode="${p.mode}"`);
      if (p.theme && p.theme !== 'light') attrs.push(`theme="${p.theme}"`);
      return `${indent}<Menu ${attrs.join(' ')} />`;
    },
  },

  tabs: {
    collectImports: (_n, c) => c.add('Tabs'),
    collectData: (node, declarations) => {
      const tabs = Array.isArray(node.props.tabs) ? node.props.tabs as string[] : [];
      const varName = `tabItems_${node.id.slice(0, 6)}`;
      const itemsDef = tabs.map((t, i) => `  { key: '${i}', label: '${t}', children: <p>${t} content</p> }`).join(',\n');
      declarations.push(`const ${varName} = [\n${itemsDef}\n  ];`);
    },
    generateJSX: (node, indent) => {
      const p = node.props;
      const varName = `tabItems_${node.id.slice(0, 6)}`;
      const attrs: string[] = [`items={${varName}}`];
      if (p.type && p.type !== 'line') attrs.push(`type="${p.type}"`);
      if (p.size && p.size !== 'default') attrs.push(`size="${p.size}"`);
      if (p.tabPosition && p.tabPosition !== 'top') attrs.push(`tabPosition="${p.tabPosition}"`);
      return `${indent}<Tabs ${attrs.join(' ')} />`;
    },
  },

  breadcrumb: {
    collectImports: (_n, c) => c.add('Breadcrumb'),
    generateJSX: (node, indent) => {
      const items = Array.isArray(node.props.items) ? node.props.items as string[] : [];
      const itemsJSX = items.map((it) => `${indent}  <Breadcrumb.Item>${escapeJSX(it)}</Breadcrumb.Item>`).join('\n');
      const attrs: string[] = [];
      if (node.props.separator && node.props.separator !== '/') attrs.push(`separator="${node.props.separator}"`);
      return `${indent}<Breadcrumb${attrs.length ? ' ' + attrs.join(' ') : ''}>\n${itemsJSX}\n${indent}</Breadcrumb>`;
    },
  },

  dropdown: {
    collectImports: (_n, c) => { c.add('Dropdown'); c.add('Button'); c.add('Menu'); },
    collectData: (node, declarations) => {
      const items = Array.isArray(node.props.items) ? node.props.items as string[] : [];
      const varName = `dropdownItems_${node.id.slice(0, 6)}`;
      const itemsDef = items.map((it, i) => `  { key: '${i}', label: '${it}' }`).join(',\n');
      declarations.push(`const ${varName} = [\n${itemsDef}\n  ];`);
    },
    generateJSX: (node, indent) => {
      const p = node.props;
      const varName = `dropdownItems_${node.id.slice(0, 6)}`;
      const attrs: string[] = [`menu={{ items: ${varName} }}`];
      if (p.placement && p.placement !== 'bottomLeft') attrs.push(`placement="${p.placement}"`);
      if (p.trigger && p.trigger !== 'hover') attrs.push(`trigger={['${p.trigger}']}`);
      return `${indent}<Dropdown ${attrs.join(' ')}>
${indent}  <Button>${escapeJSX(String(p.label ?? 'Dropdown'))}</Button>
${indent}</Dropdown>`;
    },
  },

  pagination: {
    collectImports: (_n, c) => c.add('Pagination'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.total) attrs.push(`total={${p.total}}`);
      if (p.pageSize && p.pageSize !== 10) attrs.push(`pageSize={${p.pageSize}}`);
      if (p.size && p.size !== 'default') attrs.push(`size="${p.size}"`);
      if (p.showSizeChanger) attrs.push('showSizeChanger');
      if (p.showQuickJumper) attrs.push('showQuickJumper');
      if (p.simple) attrs.push('simple');
      return `${indent}<Pagination ${attrs.join(' ')} />`;
    },
  },

  steps: {
    collectImports: (_n, c) => c.add('Steps'),
    collectData: (node, declarations) => {
      const steps = Array.isArray(node.props.steps) ? node.props.steps as string[] : [];
      const varName = `stepItems_${node.id.slice(0, 6)}`;
      const itemsDef = steps.map((s) => `  { title: '${s}' }`).join(',\n');
      declarations.push(`const ${varName} = [\n${itemsDef}\n  ];`);
    },
    generateJSX: (node, indent) => {
      const p = node.props;
      const varName = `stepItems_${node.id.slice(0, 6)}`;
      const attrs: string[] = [`items={${varName}}`];
      if (p.current !== undefined) attrs.push(`current={${p.current}}`);
      if (p.direction && p.direction !== 'horizontal') attrs.push(`direction="${p.direction}"`);
      if (p.size && p.size !== 'default') attrs.push(`size="${p.size}"`);
      return `${indent}<Steps ${attrs.join(' ')} />`;
    },
  },

  alert: {
    collectImports: (_n, c) => c.add('Alert'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.message) attrs.push(`message="${p.message}"`);
      if (p.type && p.type !== 'info') attrs.push(`type="${p.type}"`);
      if (p.closable) attrs.push('closable');
      if (p.showIcon) attrs.push('showIcon');
      if (p.banner) attrs.push('banner');
      return `${indent}<Alert ${attrs.join(' ')} />`;
    },
  },

  modal: {
    collectImports: (_n, c) => { c.add('Modal'); c.add('Button'); },
    collectState: (node, hooks) => {
      const varName = `isModal_${node.id.slice(0, 6)}`;
      if (!hooks.some((h) => h.includes(varName))) {
        hooks.push(`const [${varName}, set${capitalize(varName)}] = useState(false);`);
      }
    },
    generateJSX: (node, indent) => {
      const p = node.props;
      const varName = `isModal_${node.id.slice(0, 6)}`;
      const setVar = `set${capitalize(varName)}`;
      const attrs: string[] = [
        `title="${p.title ?? 'Modal'}"`,
        `open={${varName}}`,
        `onOk={() => ${setVar}(false)}`,
        `onCancel={() => ${setVar}(false)}`,
      ];
      if (p.okText && p.okText !== 'OK') attrs.push(`okText="${p.okText}"`);
      if (p.cancelText && p.cancelText !== 'Cancel') attrs.push(`cancelText="${p.cancelText}"`);
      if (p.centered) attrs.push('centered');
      return `${indent}<Button onClick={() => ${setVar}(true)}>Open Modal</Button>
${indent}<Modal
${indent}  ${attrs.join(`\n${indent}  `)}
${indent}>
${indent}  <p>${escapeJSX(String(p.content ?? ''))}</p>
${indent}</Modal>`;
    },
  },

  loading: {
    collectImports: (_n, c) => c.add('Spin'),
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.spinning !== undefined) attrs.push(`spinning={${p.spinning}}`);
      if (p.size && p.size !== 'default') attrs.push(`size="${p.size}"`);
      if (p.tip) attrs.push(`tip="${p.tip}"`);
      return `${indent}<Spin ${attrs.join(' ')} />`;
    },
  },

  popover: {
    collectImports: (_n, c) => { c.add('Popover'); c.add('Button'); },
    generateJSX: (node, indent) => {
      const p = node.props;
      const attrs: string[] = [];
      if (p.title) attrs.push(`title="${p.title}"`);
      if (p.content) attrs.push(`content="${p.content}"`);
      if (p.trigger && p.trigger !== 'hover') attrs.push(`trigger="${p.trigger}"`);
      if (p.placement && p.placement !== 'top') attrs.push(`placement="${p.placement}"`);
      return `${indent}<Popover ${attrs.join(' ')}>
${indent}  <Button>Hover me</Button>
${indent}</Popover>`;
    },
  },
};

function getStrategy(componentType: string): ComponentStrategy | undefined {
  // Map componentType to strategy key (lowercase first letter)
  const key = componentType.charAt(0).toLowerCase() + componentType.slice(1);
  return strategies[key] ?? strategies[componentType.toLowerCase()];
}

/* ─── Helpers ─────────────────────────────────────────── */
function escapeJSX(text: string): string {
  return text.replace(/[{}<>&"]/g, (c) => {
    const map: Record<string, string> = { '{': '&#123;', '}': '&#125;', '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;' };
    return map[c] ?? c;
  });
}

function generatePropsString(props: Record<string, unknown>, exclude: string[]): string {
  const entries = Object.entries(props).filter(
    ([k, v]) => !exclude.includes(k) && v !== undefined && v !== null && v !== '' && v !== false,
  );
  if (entries.length === 0) return '';
  return ' ' + entries.map(([k, v]) => {
    if (typeof v === 'string') return `${k}="${v}"`;
    if (typeof v === 'boolean') return k;
    return `${k}={${JSON.stringify(v)}}`;
  }).join(' ');
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
